[site]
title = "starlightr"
description = "Build beautiful Starlight documentation sites for R packages"
logo = "man/figures/logo.png"
favicon = "man/figures/logo.png"

[home]
hero = { tagline = "Build beautiful Starlight documentation sites for R packages", actions = [
	{ text = "Get Started", link = "./articles/readme/", icon = "right-arrow", variant = "primary" },
	{ text = "View on GitHub", link = "https://github.com/A2-ai/starlightr", icon = "external", variant = "minimal" },
] }
cards = [
	{ icon = "starlight", title = "Welcome to starlightr", description = "R Pacakge site generator", link = "./articles/readme/" },
	{ icon = "document", title = "Configuration File", description = "configure your site with _starlightr.toml", link = "./articles/configuration/" },
	{ icon = "document", title = "Build your site", description = "build_site reference", link = "./reference/build_site/" },
]

[sidebar]
articles = [
	{ label = "Getting Started", contents = [
		{ slug = "README", label = "Welcome" },
		"configuration",
	] },
]
reference = [
	{ label = "Site Building", contents = [
		"use_starlightr",
		"build_site",
		"audit_config",
	], collapsed = true },
	{ label = "Configuration Helpers", contents = [
		"add_action",
		"add_card",
		"add_reference",
		"add_article",
		"add_version",
		"add_package",
	] , collapsed = true },
	{ label = "Sidebar Helpers", contents = [
		"get_reference_sections",
		"get_article_sections",
		"set_reference_section",
		"set_article_section",
	], collapsed = true  },
	{ label = "Reference Rendering", contents = [
		"build_reference_files",
		"build_package_reference_docs",
		"render_reference",
	], collapsed = true  },
	{ label = "Article Building", contents = [
		"build_articles",
		"build_package_articles",
	], collapsed = true  },
]
[navbar]
right = [{ icon = "github", href = "https://github.com/A2-ai/starlightr" }]

[theme]
color_mode = "auto"

[reference]
skip_sections = ["title", "name", "alias", "doc type"]
section_order = ["Description"]
include_pagefind = true

[output]
dir = "../Docs/starlightr-docs"
include_build_files = true

[versions]
enabled = true
list = [{ tag = "0.1.0", label = "v0.1.0", default = true }]
