use_lockfile = false

[project]
name = "starlightr"
r_version = "4.5"

repositories = [
  { alias = "PRISM", url = "https://prism.dev.a2-ai.cloud/rpkgs/stratus/2025-09-29/"},
]

dependencies = [
  "devtools",
	"covr",
	{ name = "roxygen2md", git = "https://github.com/r-lib/roxygen2md", tag = "v1.0.1" },
  {name = "starlightr", path = ".", dependencies_only = true, install_suggestions = true}
]
