use_lockfile = false

[project]
name = "starlightr"
r_version = "4.5"

repositories = [
  { alias = "prism", url = "https://prism.dev.a2-ai.cloud/rpkgs/stratus/2026-01-14/" },
	{ alias = "ppm", url = "https://packagemanager.posit.co/cran/latest" },
]

dependencies = [
  "devtools",
	"covr",
  { name = "starlightr", path = ".", dependencies_only = false, install_suggestions = true },
  { name = "rextendr", git = "https://github.com/extendr/rextendr", tag = "v0.5.0" },
    "hexSticker",
]
