#' Build a Starlight documentation site for an R package
#'
#' @param pkg Path to package directory, defaults to current directory
#' @param config_file Path to _starlightr.yaml configuration file
#' @param output_dir Directory to build the site in
#' @param preview Logical, whether to open preview after building
#'
#' @return Invisibly returns the path to the built site
#' @export
#'
#' @examples \dontrun{
#' # Build site for current package (uses config default)
#' build_site()
#'
#' # Build to external directory (recommended to avoid bloat)
#' build_site(output_dir = "/path/to/my-package-docs")
#' build_site(output_dir = "../my-package-docs")
#'
#' # Build with custom configuration
#' build_site(config_file = "my_config.yaml")
#'
#' # Build to relative directory (not recommended due to Starlight bloat)
#' build_site(output_dir = "docs")
#' }
build_site <- function(pkg = ".",
                      config_file = "_starlightr.yaml",
                      output_dir = NULL,
                      preview = FALSE) {

  # Resolve package path
  pkg_path <- normalizePath(pkg, mustWork = TRUE)

  # Read configuration
  config <- read_config(file.path(pkg_path, config_file))

  # Determine output directory
  if (is.null(output_dir)) {
    output_dir <- config$output$dir %||% "docs"
  }

  # Handle absolute vs relative paths
  if (is_absolute_path(output_dir)) {
    output_path <- output_dir
  } else {
    output_path <- file.path(pkg_path, output_dir)
  }

  message("Building Starlight site for package: ", basename(pkg_path))
  message("Output directory: ", output_path)

  # Provide helpful info about external vs internal directories
  if (is_absolute_path(output_dir) || startsWith(output_dir, "..")) {
    message("Using external directory (recommended for Starlight sites)")
  } else {
    message("Using internal directory - consider external directory to avoid bloat")
  }

  # Create output directory structure
  setup_starlight_structure(output_path, config)

  # Generate initial configuration files (without astro.config.mjs since we need files first)
  generate_content_config(output_path)
  if (config$output$include_build_files %||% TRUE) {
    generate_package_json(output_path, config)
  }

  # Extract and process R documentation
  process_package_documentation(pkg_path, output_path, config)

  # Process vignettes/articles from inst/starlightr/
  process_articles(pkg_path, output_path, config)

  # Generate astro.config.mjs now that files exist for pattern matching
  generate_astro_config(output_path, config)

  # Copy assets if they exist
  copy_assets(pkg_path, output_path, config)

  # Create default index.mdx if it doesn't exist
  create_index_page(pkg_path, output_path, config)

  # Create directory index pages
  create_directory_indexes(pkg_path, output_path, config)

  message("Site built successfully!")

  if (preview) {
    preview_site(output_path)
  }

  invisible(output_path)
}

#' Read and parse starlightr configuration
#'
#' @param config_path Path to the _starlightr.yaml file
#'
#' @return List containing parsed configuration
read_config <- function(config_path) {
  if (!file.exists(config_path)) {
    message("No _starlightr.yaml found, using default configuration")
    message("Tip: Run use_starlightr() to create a configuration file")
    return(default_config())
  }

  # For now, use a simple YAML reader
  # In the future, we might want to add schema validation
  tryCatch({
    config <- yaml::yaml.load_file(config_path)

    # Merge with defaults to ensure all required fields exist
    merge_config(config, default_config())
  }, error = function(e) {
    stop("Error reading configuration file: ", e$message)
  })
}

#' Get default configuration
#'
#' @return List with default configuration values
default_config <- function() {
  list(
    site = list(
      title = "Package Documentation",
      description = "Documentation generated by starlightr"
    ),
    navbar = list(
      left = list(
        list(text = "Home", href = "index.md"),
        list(text = "Reference", href = "reference/"),
        list(text = "Articles", href = "articles/")
      )
    ),
    theme = list(
      color_mode = "auto"
    ),
    content = list(
      code_sections = c("usage", "examples"),
      skip_sections = c("name", "alias", "title", "seealso")
    ),
    output = list(
      dir = "docs",
      include_build_files = TRUE
    )
  )
}

#' Merge user config with defaults
#'
#' @param user_config User-provided configuration
#' @param default_config Default configuration
#'
#' @return Merged configuration list
merge_config <- function(user_config, default_config) {
  # Simple recursive merge - in production we'd want something more sophisticated
  utils::modifyList(default_config, user_config)
}

#' Set up Starlight directory structure
#'
#' @param output_path Path to output directory
#' @param config Configuration list
setup_starlight_structure <- function(output_path, config) {
  # Create main directories
  dirs <- c(
    output_path,
    file.path(output_path, "src"),
    file.path(output_path, "src", "content"),
    file.path(output_path, "src", "content", "docs"),
    file.path(output_path, "src", "content", "docs", "reference"),
    file.path(output_path, "src", "content", "docs", "articles"),
    file.path(output_path, "public")
  )

  for (dir in dirs) {
    if (!dir.exists(dir)) {
      dir.create(dir, recursive = TRUE)
      message("Created directory: ", dir)
    }
  }
}

#' Generate Starlight configuration files
#'
#' @param output_path Path to output directory
#' @param config Configuration list
#' @param pkg_path Path to package directory
generate_starlight_config <- function(output_path, config, pkg_path) {
  # Generate astro.config.mjs
  generate_astro_config(output_path, config)

  # Generate content.config.ts (required for Astro content collections)
  generate_content_config(output_path)

  # Generate package.json if requested
  if (config$output$include_build_files %||% TRUE) {
    generate_package_json(output_path, config)
  }
}

#' Generate astro.config.mjs file
#'
#' @param output_path Path to output directory
#' @param config Configuration list
generate_astro_config <- function(output_path, config) {
  github_url <- get_github_url(config)
  social_config <- ""

  if (!is.null(github_url)) {
    social_config <- sprintf("social: [{ icon: 'github', label: 'GitHub', href: '%s' }],", github_url)
  }

  # Generate sidebar configuration from YAML
  sidebar_config <- generate_sidebar_config(config, output_path)

  astro_config <- sprintf('// @ts-check
import { defineConfig } from "astro/config";
import starlight from "@astrojs/starlight";

// https://astro.build/config
export default defineConfig({
  integrations: [
    starlight({
      title: "%s",
      %s
      sidebar: %s
    })
  ]
});
',
    config$site$title %||% "Package Documentation",
    social_config,
    sidebar_config
  )

  writeLines(astro_config, file.path(output_path, "astro.config.mjs"))
  message("Generated astro.config.mjs")
}

#' Generate sidebar configuration for Starlight
#'
#' @param config Configuration list from YAML
#' @param output_path Path to output directory (needed for pattern matching)
#' @return JavaScript sidebar configuration as string
generate_sidebar_config <- function(config, output_path = NULL) {
  sidebar_parts <- c()

  # Handle articles section
  if (!is.null(config$sidebar$articles)) {
    articles_items <- c()
    for (group in config$sidebar$articles) {
      if (!is.null(group$title) && !is.null(group$contents)) {
        group_items <- c()
        for (content in group$contents) {
          # Convert content to slug format
          slug <- paste0("articles/", content)
          group_items <- c(group_items, sprintf('{ label: "%s", slug: "%s" }', content, slug))
        }
        # Handle collapsed field
        collapsed_attr <- ""
        if (!is.null(group$collapsed) && group$collapsed) {
          collapsed_attr <- ",\n          collapsed: true"
        }

        group_js <- sprintf('{\n          label: "%s"%s,\n          items: [\n            %s\n          ]\n        }',
                           group$title, collapsed_attr, paste(group_items, collapse = ",\n            "))
        articles_items <- c(articles_items, group_js)
      }
    }
    articles_section <- sprintf('{\n      label: "Articles",\n      items: [\n        %s\n      ]\n    }',
                               paste(articles_items, collapse = ",\n        "))
    sidebar_parts <- c(sidebar_parts, articles_section)
  } else {
    # Fallback to autogenerate
    sidebar_parts <- c(sidebar_parts, '{\n      label: "Articles",\n      autogenerate: { directory: "articles" }\n    }')
  }

  # Handle reference section
  if (!is.null(config$sidebar$reference)) {
    reference_items <- c()
    for (group in config$sidebar$reference) {
      if (!is.null(group$title) && !is.null(group$contents)) {
        group_items <- c()
        has_patterns <- any(grepl("\\*", group$contents))

        if (has_patterns && !is.null(output_path)) {
          # Handle pattern matching by finding actual files
          ref_dir <- file.path(output_path, "src", "content", "docs", "reference")
          if (dir.exists(ref_dir)) {
            all_files <- list.files(ref_dir, pattern = "\\.mdx?$", full.names = FALSE)
            all_files <- tools::file_path_sans_ext(all_files)

            # Match files against patterns in this group
            matched_files <- c()
            for (content in group$contents) {
              if (grepl("\\*$", content)) {
                # Convert pattern to regex (e.g., "extract_*" -> "^extract_")
                pattern <- paste0("^", gsub("\\*", "", content))
                matches <- all_files[grepl(pattern, all_files)]
                matched_files <- c(matched_files, matches)
              } else {
                # Exact match
                if (content %in% all_files) {
                  matched_files <- c(matched_files, content)
                }
              }
            }

            # Remove duplicates and sort
            matched_files <- unique(matched_files)
            matched_files <- sort(matched_files)

            # Create items for matched files
            for (file in matched_files) {
              slug <- paste0("reference/", file)
              group_items <- c(group_items, sprintf('{ label: "%s", slug: "%s" }', file, slug))
            }
          }
        } else {
          # No patterns, handle exact names
          for (content in group$contents) {
            if (!grepl("\\*", content)) {
              slug <- paste0("reference/", content)
              group_items <- c(group_items, sprintf('{ label: "%s", slug: "%s" }', content, slug))
            }
          }
        }

        # Add the group if we have items
        if (length(group_items) > 0) {
          # Handle collapsed field
          collapsed_attr <- ""
          if (!is.null(group$collapsed) && group$collapsed) {
            collapsed_attr <- ",\n          collapsed: true"
          }

          group_js <- sprintf('{\n          label: "%s"%s,\n          items: [\n            %s\n          ]\n        }',
                             group$title, collapsed_attr, paste(group_items, collapse = ",\n            "))
          reference_items <- c(reference_items, group_js)
        }
      }
    }

    if (length(reference_items) > 0) {
      reference_section <- sprintf('{\n      label: "Reference",\n      items: [\n        %s\n      ]\n    }',
                                  paste(reference_items, collapse = ",\n        "))
      sidebar_parts <- c(sidebar_parts, reference_section)
    } else {
      # Fallback to autogenerate if no items
      sidebar_parts <- c(sidebar_parts, '{\n      label: "Reference",\n      autogenerate: { directory: "reference" }\n    }')
    }
  } else {
    # Fallback to autogenerate
    sidebar_parts <- c(sidebar_parts, '{\n      label: "Reference",\n      autogenerate: { directory: "reference" }\n    }')
  }

  # Combine all parts
  sidebar_config <- sprintf('[\n    %s\n  ]', paste(sidebar_parts, collapse = ",\n    "))
  return(sidebar_config)
}

#' Generate package.json file
#'
#' @param output_path Path to output directory
#' @param config Configuration list
generate_package_json <- function(output_path, config) {
  package_json <- '{
  "name": "starlight-docs",
  "type": "module",
  "version": "0.0.1",
  "scripts": {
    "dev": "astro dev",
    "start": "astro dev",
    "build": "astro build",
    "preview": "astro preview",
    "astro": "astro"
  },
  "dependencies": {
    "@astrojs/starlight": "^0.36.0",
    "astro": "^5.6.1",
    "sharp": "^0.34.2"
  }
}'

  writeLines(package_json, file.path(output_path, "package.json"))
  message("Generated package.json")
}

#' Generate content.config.ts file for Astro content collections
#'
#' @param output_path Path to output directory
generate_content_config <- function(output_path) {
  content_config <- 'import { defineCollection } from "astro:content";
import { docsLoader } from "@astrojs/starlight/loaders";
import { docsSchema } from "@astrojs/starlight/schema";

export const collections = {
  docs: defineCollection({ loader: docsLoader(), schema: docsSchema() }),
};
'

  src_path <- file.path(output_path, "src")
  writeLines(content_config, file.path(src_path, "content.config.ts"))
  message("Generated content.config.ts")
}

#' Extract GitHub URL from configuration
#'
#' @param config Configuration list
#' @return GitHub URL or NULL
get_github_url <- function(config) {
  # Look for GitHub URL in navbar right section
  if (!is.null(config$navbar$right)) {
    for (item in config$navbar$right) {
      if (!is.null(item$icon) && item$icon == "github") {
        return(item$href)
      }
    }
  }
  return(NULL)
}

#' Process package documentation into Starlight format
#'
#' @param pkg_path Path to package directory
#' @param output_path Path to output directory
#' @param config Configuration list
process_package_documentation <- function(pkg_path, output_path, config) {
  message("Processing R documentation...")

  # Get the actual package name from DESCRIPTION
  pkg_name <- get_package_name(pkg_path)

  # Extract all Rd content from the package
  rd_content <- extract_package_rd_content(pkg_name)

  # Generate markdown files for each function
  ref_dir <- file.path(output_path, "src", "content", "docs", "reference")

  write_md_files(
    rd_content,
    ref_dir,
    file_ext = ".mdx",
    code_sections = config$content$code_sections %||% c("usage", "examples"),
    skip_sections = config$content$skip_sections %||% c("name", "alias", "title", "seealso")
  )

  message("Generated reference documentation")
}

#' Process articles from inst/starlightr/*.Rmd
#'
#' @param pkg_path Path to package directory
#' @param output_path Path to output directory
#' @param config Configuration list
process_articles <- function(pkg_path, output_path, config) {
  articles_source <- file.path(pkg_path, "inst", "starlightr")

  if (!dir.exists(articles_source)) {
    message("No inst/starlightr/ directory found, skipping articles")
    return()
  }

  # Find all .Rmd files
  rmd_files <- list.files(articles_source, pattern = "\\.Rmd$", full.names = TRUE)

  if (length(rmd_files) == 0) {
    message("No .Rmd files found in inst/starlightr/")
    return()
  }

  message("Processing articles...")
  articles_dir <- file.path(output_path, "src", "content", "docs", "articles")

  for (rmd_file in rmd_files) {
    process_rmd_file(rmd_file, articles_dir)
  }

  message("Generated ", length(rmd_files), " article(s)")
}

#' Process a single .Rmd file to Markdown
#'
#' @param rmd_path Path to .Rmd file
#' @param output_dir Output directory for markdown file
process_rmd_file <- function(rmd_path, output_dir) {
  # For now, simple conversion - in the future we could use knitr/rmarkdown
  base_name <- tools::file_path_sans_ext(basename(rmd_path))
  output_file <- file.path(output_dir, paste0(base_name, ".mdx"))

  # Read the .Rmd file
  content <- readLines(rmd_path)

  # Process frontmatter - keep existing or add default
  has_frontmatter <- length(content) > 0 && grepl("^---", content[1])

  if (has_frontmatter) {
    # Keep existing frontmatter
    writeLines(content, output_file)
  } else {
    # Add default frontmatter
    title <- tools::toTitleCase(gsub("[-_]", " ", base_name))
    frontmatter <- c("---", paste0("title: \"", title, "\""), "---", "")
    full_content <- c(frontmatter, content)
    writeLines(full_content, output_file)
  }
  message("Processed: ", basename(rmd_path))
}

#' Create default index.mdx page
#'
#' @param pkg_path Path to package directory
#' @param output_path Path to output directory
#' @param config Configuration list
create_index_page <- function(pkg_path, output_path, config) {
  index_path <- file.path(output_path, "src", "content", "docs", "index.mdx")

  # Don't overwrite existing index
  if (file.exists(index_path)) {
    return()
  }

  # Get package info
  pkg_name <- get_package_name(pkg_path)
  pkg_desc <- config$site$description %||% "Documentation generated by starlightr"

  # Get hero configuration from YAML
  hero_tagline <- config$home$hero$tagline %||% pkg_desc
  hero_actions <- ""

  if (!is.null(config$home$hero$actions)) {
    actions_yaml <- c()
    for (action in config$home$hero$actions) {
      action_yaml <- sprintf('    - text: %s\n      link: %s\n      icon: %s\n      variant: %s',
                            action$text %||% "Get Started",
                            action$link %||% "/articles/getting-started/",
                            action$icon %||% "right-arrow",
                            action$variant %||% "primary")
      actions_yaml <- c(actions_yaml, action_yaml)
    }
    hero_actions <- paste(actions_yaml, collapse = "\n")
  } else {
    # Default actions
    github_url <- get_github_url(config) %||% "https://github.com/user/repo"
    hero_actions <- sprintf('    - text: Get Started
      link: /articles/getting-started/
      icon: right-arrow
      variant: primary
    - text: View on GitHub
      link: %s
      icon: external
      variant: minimal', github_url)
  }

  # Create default index content with Starlight components
  index_content <- sprintf('---
title: "Welcome to %s"
description: "%s"
template: splash
hero:
  tagline: %s
  actions:
%s
---

import { Card, CardGrid } from "@astrojs/starlight/components";

## Quick links

<CardGrid stagger>
  <Card title="Function Reference" icon="list-format">
    Complete API documentation for all functions.
    [Browse Reference >](/reference/)
  </Card>
  <Card title="Articles & Guides" icon="open-book">
    Learn how to use the package with step-by-step guides.
    [Read Articles >](/articles/)
  </Card>
  <Card title="View Source" icon="github">
    Explore the source code and contribute to the project.
    [GitHub Repository >](%s)
  </Card>
  <Card title="Get Help" icon="information">
    Found a bug or need help? Open an issue or discussion.
    [Get Support >](%s/issues)
  </Card>
</CardGrid>
',
    pkg_name,
    pkg_desc,
    hero_tagline,
    hero_actions,
    get_github_url(config) %||% "https://github.com/user/repo",
    get_github_url(config) %||% "https://github.com/user/repo"
  )

  writeLines(index_content, index_path)
  message("Created default index.mdx")
}

#' Create directory index pages for articles and reference
#'
#' @param pkg_path Path to package directory
#' @param output_path Path to output directory
#' @param config Configuration list
create_directory_indexes <- function(pkg_path, output_path, config) {
  docs_path <- file.path(output_path, "src", "content", "docs")

  # Create articles index
  articles_index_path <- file.path(docs_path, "articles", "index.mdx")
  if (!file.exists(articles_index_path)) {
    pkg_name <- get_package_name(pkg_path)
    articles_content <- sprintf('---
title: "Articles & Guides"
description: "Learn how to use %s with step-by-step guides and tutorials"
---

# Articles & Guides

This section contains guides and tutorials to help you get started with %s and learn about its advanced features.

## Available Articles

Browse the articles in the sidebar to get started!

', pkg_name, pkg_name)

    writeLines(articles_content, articles_index_path)
    message("Created articles/index.mdx")
  }

  # Create reference index
  reference_index_path <- file.path(docs_path, "reference", "index.mdx")
  if (!file.exists(reference_index_path)) {
    pkg_name <- get_package_name(pkg_path)
    reference_content <- sprintf('---
title: "Function Reference"
description: "Complete API documentation for all %s functions"
---

# Function Reference

This section contains detailed documentation for all functions in the %s package.

## Available Functions

Browse the functions in the sidebar to explore the complete API documentation.

', pkg_name, pkg_name)

    writeLines(reference_content, reference_index_path)
    message("Created reference/index.mdx")
  }
}

#' Copy assets from package to site
#'
#' @param pkg_path Path to package directory
#' @param output_path Path to output directory
#' @param config Configuration list
copy_assets <- function(pkg_path, output_path, config) {
  # Copy common assets if they exist
  assets_to_check <- c(
    "inst/starlightr/assets",
    "inst/starlightr/public",
    "man/figures"
  )

  public_dir <- file.path(output_path, "public")

  for (asset_path in assets_to_check) {
    full_path <- file.path(pkg_path, asset_path)
    if (dir.exists(full_path)) {
      file.copy(full_path, public_dir, recursive = TRUE)
      message("Copied assets from: ", asset_path)
    }
  }
}

#' Preview the generated site
#'
#' @param output_path Path to built site
preview_site <- function(output_path) {
  message("To preview your site:")
  message("1. cd ", output_path)
  message("2. npm install")
  message("3. npm run dev")
}

# Utility function for null-or-default assignment
`%||%` <- function(a, b) if (is.null(a)) b else a

#' Check if a path is absolute
#'
#' @param path Character string representing a file path
#' @return Logical indicating if the path is absolute
is_absolute_path <- function(path) {
  # Check for Unix-style absolute paths (starting with /)
  if (grepl("^/", path)) return(TRUE)

  # Check for Windows-style absolute paths (C:\ or \\)
  if (grepl("^[A-Za-z]:", path) || grepl("^\\\\", path)) return(TRUE)

  # Check for tilde expansion (~)
  if (grepl("^~", path)) return(TRUE)

  return(FALSE)
}

#' Get package name from DESCRIPTION file
#'
#' @param pkg_path Path to package directory
#' @return Package name as string
get_package_name <- function(pkg_path) {
  desc_path <- file.path(pkg_path, "DESCRIPTION")

  if (!file.exists(desc_path)) {
    stop("DESCRIPTION file not found in: ", pkg_path)
  }

  desc_lines <- readLines(desc_path)
  name_line <- grep("^Package:", desc_lines, value = TRUE)

  if (length(name_line) == 0) {
    stop("Package name not found in DESCRIPTION file")
  }

  pkg_name <- trimws(sub("^Package:\\s*", "", name_line[1]))
  return(pkg_name)
}

#' Initialize starlightr for a package
#'
#' Sets up the necessary files and configuration for using starlightr.
#' Creates a default _starlightr.yaml configuration file, updates .Rbuildignore,
#' and creates the inst/starlightr/ directory structure.
#'
#' @param pkg Path to package directory, defaults to current directory
#' @param open Logical, whether to open the configuration file for editing
#'
#' @return Invisibly returns TRUE if successful
#' @export
#'
#' @examples \dontrun{
#' # Initialize starlightr for current package
#' use_starlightr()
#'
#' # Initialize for a specific package
#' use_starlightr("/path/to/my/package")
#' }
use_starlightr <- function(pkg = ".", open = interactive()) {
  # Resolve package path
  pkg_path <- normalizePath(pkg, mustWork = TRUE)

  message("Setting up starlightr for package: ", basename(pkg_path))

  # Create _starlightr.yaml if it doesn't exist
  config_path <- file.path(pkg_path, "_starlightr.yaml")
  if (!file.exists(config_path)) {
    create_default_config(config_path, pkg_path)
    cli::cli_alert_success("Created _starlightr.yaml")
  } else {
    cli::cli_alert_info("_starlightr.yaml already exists")
  }

  # Update .Rbuildignore
  update_rbuildignore(pkg_path)

  # Create inst/starlightr directory
  articles_dir <- file.path(pkg_path, "inst", "starlightr")
  if (!dir.exists(articles_dir)) {
    dir.create(articles_dir, recursive = TRUE)

    # Create a sample article
    create_sample_article(articles_dir)
    cli::cli_alert_success("Created inst/starlightr/ directory with sample article")
  } else {
    cli::cli_alert_info("inst/starlightr/ directory already exists")
  }

  cli::cli_alert_success("starlightr setup complete!")
  message("  - Edit _starlightr.yaml to customize your site")
  message("  - Add .Rmd files to inst/starlightr/ for articles")
  message("  - Run build_site() to generate your documentation")

  if (open && file.exists(config_path)) {
    utils::file.edit(config_path)
  }

  invisible(TRUE)
}

#' Create default _starlightr.yaml configuration
#'
#' @param config_path Path where to create the config file
#' @param pkg_path Path to package directory
create_default_config <- function(config_path, pkg_path) {
  # Try to read DESCRIPTION to get package info
  desc_path <- file.path(pkg_path, "DESCRIPTION")
  pkg_name <- basename(pkg_path)
  pkg_desc <- "Documentation generated by starlightr"

  if (file.exists(desc_path)) {
    tryCatch({
      desc_lines <- readLines(desc_path)

      # Extract package name
      name_line <- grep("^Package:", desc_lines, value = TRUE)
      if (length(name_line) > 0) {
        pkg_name <- trimws(sub("^Package:\\s*", "", name_line[1]))
      }

      # Extract description
      desc_line <- grep("^Description:", desc_lines, value = TRUE)
      if (length(desc_line) > 0) {
        pkg_desc <- trimws(sub("^Description:\\s*", "", desc_line[1]))
      }
    }, error = function(e) {
      # Use defaults if can't read DESCRIPTION
    })
  }

  config_content <- sprintf('# starlightr configuration file
# This file defines how your R package documentation will be built into a Starlight site

# Site metadata
site:
  title: "%s"
  description: "%s"

# Home page configuration
home:
  hero:
    tagline: "%s"
    actions:
      - text: "Get Started"
        link: "/articles/getting-started/"
        icon: "right-arrow"
        variant: "primary"
      - text: "View on GitHub"
        link: "https://github.com/user/repo"  # Update this!
        icon: "external"
        variant: "minimal"

# Sidebar configuration for different sections
sidebar:
  articles:
    # Custom organization of vignettes/articles
    - title: "Getting Started"
      contents:
        - "introduction"
        - "getting-started"
    # Example of collapsed group:
    # - title: "Advanced Topics"
    #   collapsed: true
    #   contents:
    #     - "advanced-usage"
    #     - "customization"

  reference:
    # Organize functions into groups
    - title: "Site Building"
      contents:
        - "build_site"
        - "use_starlightr"
    - title: "Documentation Processing"
      collapsed: true  # Start this group collapsed
      contents:
        - "extract_*"  # Functions matching pattern will use autogenerate
        - "process_*"
        - "get_rd_tags"
    - title: "Formatting & Output"
      collapsed: true  # Start this group collapsed
      contents:
        - "format_*"
        - "write_*"
        - "clean_text"

# Theme and appearance
theme:
  color_mode: "auto"  # light, dark, or auto

# Content processing options
content:
  # Custom sections to format as code
  code_sections:
    - "usage"
    - "examples"

  # Sections to skip entirely
  skip_sections:
    - "seealso"
    - "name"

# Output directory for generated site
output:
  dir: "../%s-docs"  # External directory (recommended)
  # dir: "docs"       # Internal directory (not recommended due to bloat)
  include_build_files: true
', pkg_name, pkg_desc, pkg_desc, pkg_name)

  writeLines(config_content, config_path)

  # Ensure file ends with newline to avoid warnings
  cat("\n", file = config_path, append = TRUE)
}

#' Update .Rbuildignore to include _starlightr.yaml
#'
#' @param pkg_path Path to package directory
update_rbuildignore <- function(pkg_path) {
  rbuildignore_path <- file.path(pkg_path, ".Rbuildignore")

  # Create .Rbuildignore if it doesn't exist
  if (!file.exists(rbuildignore_path)) {
    writeLines("^_starlightr\\.yaml$", rbuildignore_path)
    cli::cli_alert_success("Created .Rbuildignore with _starlightr.yaml")
    return()
  }

  # Read existing .Rbuildignore
  existing_lines <- readLines(rbuildignore_path)

  # Check if _starlightr.yaml is already ignored
  pattern_exists <- any(grepl("_starlightr", existing_lines, fixed = TRUE))

  if (!pattern_exists) {
    # Add the pattern
    updated_lines <- c(existing_lines, "^_starlightr\\.yaml$")
    writeLines(updated_lines, rbuildignore_path)
    cli::cli_alert_success("Updated .Rbuildignore to include _starlightr.yaml")
  } else {
    cli::cli_alert_info(".Rbuildignore already includes _starlightr.yaml pattern")
  }
}

#' Create a sample article in inst/starlightr/
#'
#' @param articles_dir Path to inst/starlightr directory
create_sample_article <- function(articles_dir) {
  sample_content <- '---
title: "Getting Started"
description: "Introduction to using this package"
---

# Getting Started

This is a sample article created by starlightr.

## Installation

You can install this package from GitHub:

```r
# Install from GitHub
devtools::install_github("user/repo")
```

## Basic Usage

Here\'s how to use the main functions:

```r
library(packagename)

# Example usage
result <- main_function()
```

## Next Steps

- Edit this file to add your own content
- Create additional .Rmd files in inst/starlightr/
- Run `starlightr::build_site()` to generate your documentation site
'

  sample_path <- file.path(articles_dir, "getting-started.Rmd")
  writeLines(sample_content, sample_path)

  # Also create an introduction article as backup
  intro_content <- '---
title: "Introduction"
description: "Introduction to using this package"
---

# Introduction

Welcome to the package documentation!

## Overview

This package provides tools for [describe main functionality].

## Quick Start

Here\'s a simple example to get you started:

```r
library(packagename)

# Your first example
result <- main_function()
```

## Next Steps

- Browse the [Function Reference](/reference/) for detailed API documentation
- Check out more [Articles & Guides](/articles/) for advanced usage
'

  intro_path <- file.path(articles_dir, "introduction.Rmd")
  if (!file.exists(intro_path)) {
    writeLines(intro_content, intro_path)
  }
}