#' Build a Starlight documentation site for an R package
#'
#' @param pkg Path to package directory, defaults to current directory
#' @param config_file Path to _starlightr.yaml configuration file
#' @param output_dir Directory to build the site in
#' @param preview Logical, whether to open preview after building
#'
#' @return Invisibly returns the path to the built site
#' @export
#'
#' @examples \dontrun{
#' # Build site for current package (uses config default)
#' build_site()
#'
#' # Build to external directory (recommended to avoid bloat)
#' build_site(output_dir = "/path/to/my-package-docs")
#' build_site(output_dir = "../my-package-docs")
#'
#' # Build with custom configuration
#' build_site(config_file = "my_config.yaml")
#'
#' # Build to relative directory (not recommended due to Starlight bloat)
#' build_site(output_dir = "docs")
#' }
build_site <- function(pkg = ".",
                      config_file = "_starlightr.yaml",
                      output_dir = NULL,
                      preview = FALSE) {

  # Resolve package path
  pkg_path <- normalizePath(pkg, mustWork = TRUE)

  # Read configuration
  config <- read_config(file.path(pkg_path, config_file))

  # Determine output directory
  if (is.null(output_dir)) {
    output_dir <- config$output$dir %||% "docs"
  }

  # Handle absolute vs relative paths
  if (is_absolute_path(output_dir)) {
    output_path <- output_dir
  } else {
    output_path <- file.path(pkg_path, output_dir)
  }

  cli::cli_h1("Building Starlight site for {.pkg {basename(pkg_path)}}")
  cli::cli_alert_info("Output directory: {.path {output_path}}")

  # Provide helpful info about external vs internal directories
  if (is_absolute_path(output_dir) || startsWith(output_dir, "..")) {
    cli::cli_alert_info("Using external directory (recommended for Starlight sites)")
  } else {
    cli::cli_alert_warning("Using internal directory - consider external directory to avoid bloat")
  }

  # Create output directory structure
  setup_starlight_structure(output_path, config)

  # Generate initial configuration files (without astro.config.mjs since we need files first)
  generate_content_config(output_path)
  if (config$output$include_build_files %||% TRUE) {
    generate_package_json(output_path, config)
  }

  # Extract and process R documentation
  process_package_documentation(pkg_path, output_path, config)

  # Process vignettes/articles only if configured in sidebar
  if (!is.null(config$sidebar$articles)) {
    process_articles(pkg_path, output_path, config)
  }

  # Generate astro.config.mjs now that files exist for pattern matching
  generate_astro_config(output_path, config, pkg_path)

  # Copy assets if they exist
  copy_assets(pkg_path, output_path, config)

  # Copy logo and favicon if configured
  copy_branding_assets(pkg_path, output_path, config)

  # Create default index.mdx if it doesn't exist
  create_index_page(pkg_path, output_path, config)

  # Create directory index pages
  create_directory_indexes(pkg_path, output_path, config)

  cli::cli_alert_success("Site built successfully!")

  if (preview) {
    preview_site(output_path)
  }

  invisible(output_path)
}

#' Read and parse starlightr configuration
#'
#' @param config_path Path to the _starlightr.yaml file
#'
#' @return List containing parsed configuration
read_config <- function(config_path) {
  if (!file.exists(config_path)) {
    cli::cli_alert_info("No _starlightr.yaml found, using default configuration")
    cli::cli_alert("Tip: Run {.fn use_starlightr} to create a configuration file")
    return(default_config())
  }

  # For now, use a simple YAML reader
  # In the future, we might want to add schema validation
  tryCatch({
    config <- yaml::yaml.load_file(config_path)

    # Merge with defaults to ensure all required fields exist
    merge_config(config, default_config())
  }, error = function(e) {
    stop("Error reading configuration file: ", e$message)
  })
}

#' Get default configuration
#'
#' @return List with default configuration values
default_config <- function() {
  list(
    site = list(
      title = "Package Documentation",
      description = "Documentation generated by starlightr"
    ),
    navbar = list(
      left = list(
        list(text = "Home", href = "index.md"),
        list(text = "Reference", href = "reference/"),
        list(text = "Articles", href = "articles/")
      )
    ),
    theme = list(
      color_mode = "auto"
    ),
    content = list(
      code_sections = c("usage", "examples"),
      skip_sections = c("name", "alias", "title", "seealso")
    ),
    output = list(
      dir = "docs",
      include_build_files = TRUE
    )
  )
}

#' Merge user config with defaults
#'
#' @param user_config User-provided configuration
#' @param default_config Default configuration
#'
#' @return Merged configuration list
merge_config <- function(user_config, default_config) {
  # Simple recursive merge - in production we'd want something more sophisticated
  utils::modifyList(default_config, user_config)
}

#' Set up Starlight directory structure
#'
#' @param output_path Path to output directory
#' @param config Configuration list
setup_starlight_structure <- function(output_path, config) {
  # Create main directories
  dirs <- c(
    output_path,
    file.path(output_path, "src"),
    file.path(output_path, "src", "content"),
    file.path(output_path, "src", "content", "docs"),
    file.path(output_path, "src", "content", "docs", "reference"),
    file.path(output_path, "public")
  )

  # Only create articles dir if configured
  if (!is.null(config$sidebar$articles)) {
    dirs <- c(dirs, file.path(output_path, "src", "content", "docs", "articles"))
  }

  for (dir in dirs) {
    if (!dir.exists(dir)) {
      dir.create(dir, recursive = TRUE)
    }
  }
}

#' Generate Starlight configuration files
#'
#' @param output_path Path to output directory
#' @param config Configuration list
#' @param pkg_path Path to package directory
generate_starlight_config <- function(output_path, config, pkg_path) {
  # Generate astro.config.mjs
  generate_astro_config(output_path, config, pkg_path)

  # Generate content.config.ts (required for Astro content collections)
  generate_content_config(output_path)

  # Generate package.json if requested
  if (config$output$include_build_files %||% TRUE) {
    generate_package_json(output_path, config)
  }
}

#' Generate astro.config.mjs file
#'
#' @param output_path Path to output directory
#' @param config Configuration list
#' @param pkg_path Path to package directory
generate_astro_config <- function(output_path, config, pkg_path = NULL) {
  github_url <- get_github_url(config)
  social_config <- ""

  if (!is.null(github_url)) {
    social_config <- sprintf("social: [{ icon: 'github', label: 'GitHub', href: '%s' }],", github_url)
  }

  # Logo configuration
  logo_config <- ""
  if (!is.null(config$site$logo)) {
    logo_config <- 'logo: { src: "./src/assets/logo.png", alt: "Logo" },'
  }

  # Favicon configuration
  favicon_config <- ""
  if (!is.null(config$site$favicon)) {
    favicon_config <- 'favicon: "/images/favicon.png",'
  }

  # Generate sidebar configuration from YAML
  pkg_name <- if (!is.null(pkg_path)) get_package_name(pkg_path) else NULL
  sidebar_config <- generate_sidebar_config(config, output_path, pkg_name)

  astro_config <- sprintf('// @ts-check
import { defineConfig } from "astro/config";
import starlight from "@astrojs/starlight";

// https://astro.build/config
export default defineConfig({
  integrations: [
    starlight({
      title: "%s",
      %s
      %s
      %s
      sidebar: %s
    })
  ]
});
',
    config$site$title %||% "Package Documentation",
    logo_config,
    favicon_config,
    social_config,
    sidebar_config
  )

  writeLines(astro_config, file.path(output_path, "astro.config.mjs"))
  cli::cli_alert_success("Generated {.file astro.config.mjs}")
}

#' Generate sidebar configuration for Starlight
#'
#' @param config Configuration list from YAML
#' @param output_path Path to output directory (needed for pattern matching)
#' @param pkg_name Package name (for Rd database lookups)
#' @return JavaScript sidebar configuration as string
generate_sidebar_config <- function(config, output_path = NULL, pkg_name = NULL) {
  sidebar_parts <- c()

  # Handle articles section
  if (!is.null(config$sidebar$articles)) {
    articles_items <- c()
    for (group in config$sidebar$articles) {
      if (!is.null(group$label) && !is.null(group$contents)) {
        group_items <- c()
        for (content in group$contents) {
          # Convert content to slug format
          slug <- paste0("articles/", content)
          # Escape quotes for JavaScript
          escaped_content <- gsub('"', '\\"', content, fixed = TRUE)
          escaped_slug <- gsub('"', '\\"', slug, fixed = TRUE)
          group_items <- c(group_items, sprintf('{ label: "%s", slug: "%s" }', escaped_content, escaped_slug))
        }
        # Handle collapsed field
        collapsed_attr <- ""
        if (!is.null(group$collapsed) && group$collapsed) {
          collapsed_attr <- ",\n          collapsed: true"
        }

        group_js <- sprintf('{\n          label: "%s"%s,\n          items: [\n            %s\n          ]\n        }',
                           group$label, collapsed_attr, paste(group_items, collapse = ",\n            "))
        articles_items <- c(articles_items, group_js)
      }
    }
    articles_section <- sprintf('{\n      label: "Articles",\n      items: [\n        %s\n      ]\n    }',
                               paste(articles_items, collapse = ",\n        "))
    sidebar_parts <- c(sidebar_parts, articles_section)
  }
  # No else - if articles not in config, don't add to sidebar

  # Handle reference section
  if (!is.null(config$sidebar$reference)) {
    reference_items <- c()
    for (group in config$sidebar$reference) {
      # Handle flat structure: label + contents
      if (!is.null(group$label) && !is.null(group$contents)) {
        group_items <- c()
        has_patterns <- any(grepl("\\*", group$contents))

        if (has_patterns && !is.null(output_path)) {
          # Handle pattern matching by finding actual files
          ref_dir <- file.path(output_path, "src", "content", "docs", "reference")
          if (dir.exists(ref_dir)) {
            all_files <- list.files(ref_dir, pattern = "\\.mdx?$", full.names = FALSE)
            all_files <- tools::file_path_sans_ext(all_files)

            # Match files against patterns in this group
            matched_files <- c()
            for (content in group$contents) {
              if (grepl("\\*$", content)) {
                # Convert pattern to regex (e.g., "extract_*" -> "^extract_")
                pattern <- paste0("^", gsub("\\*", "", content))
                matches <- all_files[grepl(pattern, all_files)]
                matched_files <- c(matched_files, matches)
              } else {
                # Exact match
                if (content %in% all_files) {
                  matched_files <- c(matched_files, content)
                }
              }
            }

            # Remove duplicates and sort
            matched_files <- unique(matched_files)
            matched_files <- sort(matched_files)

            # Create items for matched files
            for (file in matched_files) {
              slug <- paste0("reference/", file)
              # Escape quotes for JavaScript
              escaped_file <- gsub('"', '\\"', file, fixed = TRUE)
              escaped_slug <- gsub('"', '\\"', slug, fixed = TRUE)
              group_items <- c(group_items, sprintf('{ label: "%s", slug: "%s" }', escaped_file, escaped_slug))
            }
          }
        } else {
          # No patterns, handle exact names and selectors
          expanded_contents <- expand_pkgdown_selectors(group$contents, output_path)
          for (content in expanded_contents) {
            if (!grepl("\\*", content)) {
              # Map function to its actual documentation file
              doc_file <- find_function_doc_file(content, pkg_name)
              if (!is.null(doc_file)) {
                slug <- paste0("reference/", doc_file)
                # Escape quotes for JavaScript
                escaped_content <- gsub('"', '\\"', content, fixed = TRUE)
                escaped_slug <- gsub('"', '\\"', slug, fixed = TRUE)
                group_items <- c(group_items, sprintf('{ label: "%s", slug: "%s" }', escaped_content, escaped_slug))
              }
            }
          }
        }

        # Add the group if we have items
        if (length(group_items) > 0) {
          # Handle collapsed field
          collapsed_attr <- ""
          if (!is.null(group$collapsed) && group$collapsed) {
            collapsed_attr <- ",\n          collapsed: true"
          }

          group_js <- sprintf('{\n          label: "%s"%s,\n          items: [\n            %s\n          ]\n        }',
                             group$label, collapsed_attr, paste(group_items, collapse = ",\n            "))
          reference_items <- c(reference_items, group_js)
        }
      }
      # Handle nested structure: label + items (each item has label + contents)
      else if (!is.null(group$label) && !is.null(group$items)) {
        nested_items <- c()

        for (subgroup in group$items) {
          if (!is.null(subgroup$label) && !is.null(subgroup$contents)) {
            subgroup_items <- c()

            # Process each function in the subgroup contents
            expanded_contents <- expand_pkgdown_selectors(subgroup$contents, output_path)
            for (content in expanded_contents) {
              # Map function to its actual documentation file
              doc_file <- find_function_doc_file(content, pkg_name)
              if (!is.null(doc_file)) {
                slug <- paste0("reference/", doc_file)
                # Escape quotes for JavaScript
                escaped_content <- gsub('"', '\\"', content, fixed = TRUE)
                escaped_slug <- gsub('"', '\\"', slug, fixed = TRUE)
                subgroup_items <- c(subgroup_items, sprintf('{ label: "%s", slug: "%s" }', escaped_content, escaped_slug))
              }
            }

            # Handle collapsed field for subgroups
            subcollapsed_attr <- ""
            if (!is.null(subgroup$collapsed) && subgroup$collapsed) {
              subcollapsed_attr <- ",\n            collapsed: true"
            }

            # Create subgroup JavaScript
            subgroup_js <- sprintf('{\n            label: "%s"%s,\n            items: [\n              %s\n            ]\n          }',
                                   subgroup$label, subcollapsed_attr, paste(subgroup_items, collapse = ",\n              "))
            nested_items <- c(nested_items, subgroup_js)
          }
        }

        if (length(nested_items) > 0) {
          # Handle collapsed field for main group
          collapsed_attr <- ""
          if (!is.null(group$collapsed) && group$collapsed) {
            collapsed_attr <- ",\n          collapsed: true"
          }

          group_js <- sprintf('{\n          label: "%s"%s,\n          items: [\n            %s\n          ]\n        }',
                             group$label, collapsed_attr, paste(nested_items, collapse = ",\n            "))
          reference_items <- c(reference_items, group_js)
        }
      }
    }

    if (length(reference_items) > 0) {
      reference_section <- sprintf('{\n      label: "Reference",\n      items: [\n        %s\n      ]\n    }',
                                  paste(reference_items, collapse = ",\n        "))
      sidebar_parts <- c(sidebar_parts, reference_section)
    } else {
      # Fallback to autogenerate if no items
      sidebar_parts <- c(sidebar_parts, '{\n      label: "Reference",\n      autogenerate: { directory: "reference" }\n    }')
    }
  } else {
    # Fallback to autogenerate
    sidebar_parts <- c(sidebar_parts, '{\n      label: "Reference",\n      autogenerate: { directory: "reference" }\n    }')
  }

  # Combine all parts
  sidebar_config <- sprintf('[\n    %s\n  ]', paste(sidebar_parts, collapse = ",\n    "))
  return(sidebar_config)
}

#' Generate package.json file
#'
#' @param output_path Path to output directory
#' @param config Configuration list
generate_package_json <- function(output_path, config) {
  package_json <- '{
  "name": "starlight-docs",
  "type": "module",
  "version": "0.0.1",
  "scripts": {
    "dev": "astro dev",
    "start": "astro dev",
    "build": "astro build",
    "preview": "astro preview",
    "astro": "astro"
  },
  "dependencies": {
    "@astrojs/starlight": "^0.36.0",
    "astro": "^5.6.1",
    "sharp": "^0.34.2"
  }
}'

  writeLines(package_json, file.path(output_path, "package.json"))
  cli::cli_alert_success("Generated {.file package.json}")
}

#' Generate content.config.ts file for Astro content collections
#'
#' @param output_path Path to output directory
generate_content_config <- function(output_path) {
  content_config <- 'import { defineCollection } from "astro:content";
import { docsLoader } from "@astrojs/starlight/loaders";
import { docsSchema } from "@astrojs/starlight/schema";

export const collections = {
  docs: defineCollection({ loader: docsLoader(), schema: docsSchema() }),
};
'

  src_path <- file.path(output_path, "src")
  writeLines(content_config, file.path(src_path, "content.config.ts"))
  cli::cli_alert_success("Generated {.file content.config.ts}")
}

#' Extract GitHub URL from configuration
#'
#' @param config Configuration list
#' @return GitHub URL or NULL
get_github_url <- function(config) {
  # Look for GitHub URL in navbar right section
  if (!is.null(config$navbar$right)) {
    for (item in config$navbar$right) {
      if (!is.null(item$icon) && item$icon == "github") {
        return(item$href)
      }
    }
  }
  return(NULL)
}

#' Process package documentation into Starlight format
#'
#' @param pkg_path Path to package directory
#' @param output_path Path to output directory
#' @param config Configuration list
process_package_documentation <- function(pkg_path, output_path, config) {
  cli::cli_alert_info("Processing R documentation...")

  # Get the actual package name from DESCRIPTION
  pkg_name <- get_package_name(pkg_path)

  # Get Rd database directly from tools (new approach)
  rd_db <- tryCatch(
    tools::Rd_db(pkg_name),
    error = function(e) {
      cli::cli_abort(c(
        "Failed to load Rd documentation for package {.pkg {pkg_name}}",
        "i" = "Make sure the package is installed: {.code install.packages('{pkg_name}')}"
      ))
    }
  )

  if (length(rd_db) == 0) {
    cli::cli_warn("No Rd files found in package {.pkg {pkg_name}}")
    return()
  }

  # Capture example outputs before generating markdown
  cli::cli_alert_info("Capturing example outputs...")
  artifact_dir <- file.path(output_path, "public", "examples")
  text_output_dir <- file.path(output_path, "public", "examples", "text")

  tryCatch({
    capture_example_output(pkg_name, artifact_dir, text_output_dir)
    cli::cli_alert_success("Example outputs captured successfully")
  }, error = function(e) {
    cli::cli_warn(c(
      "Could not capture example outputs: {e$message}",
      "i" = "Examples will show code only (no outputs)"
    ))
  })

  # Generate markdown files for each function
  ref_dir <- file.path(output_path, "src", "content", "docs", "reference")

  # Build config for rd_to_markdown
  md_config <- list(
    skip_sections = config$content$skip_sections %||% c("alias", "keyword", "concept"),
    arguments_format = "table",
    include_title = TRUE,
    include_frontmatter = TRUE
  )

  write_md_files(
    rd_db = rd_db,
    output_dir = ref_dir,
    file_ext = ".mdx",
    config = md_config,
    site_output_path = output_path,
    pkg_name = pkg_name
  )

  cli::cli_alert_success("Generated reference documentation for {length(rd_db)} functions")
}

#' Process articles from vignettes/*.Rmd
#'
#' @param pkg_path Path to package directory
#' @param output_path Path to output directory
#' @param config Configuration list
process_articles <- function(pkg_path, output_path, config) {
  articles_source <- file.path(pkg_path, "vignettes")

  if (!dir.exists(articles_source)) {
    cli::cli_alert_info("No vignettes/ directory found, skipping articles")
    return()
  }

  # Find all .Rmd files
  rmd_files <- list.files(articles_source, pattern = "\\.Rmd$", full.names = TRUE)

  if (length(rmd_files) == 0) {
    cli::cli_alert_info("No .Rmd files found in vignettes/")
    return()
  }

  cli::cli_alert_info("Processing articles...")
  articles_dir <- file.path(output_path, "src", "content", "docs", "articles")

  for (rmd_file in rmd_files) {
    process_rmd_file(rmd_file, articles_dir)
  }

  cli::cli_alert_success("Generated {length(rmd_files)} article{?s}")
}

#' Process a single .Rmd file to Markdown
#'
#' @param rmd_path Path to .Rmd file
#' @param output_dir Output directory for markdown file
process_rmd_file <- function(rmd_path, output_dir) {
  # Properly render Rmd using rmarkdown/knitr
  base_name <- tools::file_path_sans_ext(basename(rmd_path))

  # Create temporary directory for rendering
  temp_dir <- tempdir()
  temp_md <- file.path(temp_dir, paste0(base_name, ".md"))

  # Render Rmd to Markdown using GFM variant (fenced code blocks for MDX compatibility)
  if (requireNamespace("rmarkdown", quietly = TRUE)) {
    rmarkdown::render(
      input = rmd_path,
      output_format = rmarkdown::md_document(variant = "gfm", preserve_yaml = FALSE),
      output_file = temp_md,
      quiet = TRUE
    )
  } else if (requireNamespace("knitr", quietly = TRUE)) {
    # Fallback to knitr if rmarkdown not available
    knitr::knit(input = rmd_path, output = temp_md, quiet = TRUE)
  } else {
    stop("Neither rmarkdown nor knitr is available. Install one of these packages to process vignettes.")
  }

  # Read the rendered markdown
  rendered_content <- readLines(temp_md, warn = FALSE)

  # Post-process markdown for MDX compatibility
  rendered_md <- paste(rendered_content, collapse = "\n")

  # Fix lifecycle badge image paths (use CDN)
  rendered_md <- gsub(
    "\\.\\./help/figures/lifecycle-([a-z]+)\\.svg",
    "https://lifecycle.r-lib.org/articles/figures/lifecycle-\\1.svg",
    rendered_md
  )
  rendered_md <- gsub("\\.\\./help/figures/", "/figures/", rendered_md)

  # Escape angle brackets for MDX compatibility
  rendered_md <- escape_angle_brackets(rendered_md)
  rendered_content <- strsplit(rendered_md, "\n", fixed = TRUE)[[1]]

  # Convert to MDX and clean up frontmatter
  output_file <- file.path(output_dir, paste0(base_name, ".mdx"))

  # Add simple frontmatter since we stripped the original
  title <- tools::toTitleCase(gsub("[-_]", " ", base_name))
  final_content <- c("---", paste0("title: \"", title, "\""), "---", "", rendered_content)

  writeLines(final_content, output_file)

  # Clean up temp file
  if (file.exists(temp_md)) {
    unlink(temp_md)
  }
}

#' Update hero image in existing index.mdx
#'
#' @param index_path Path to index.mdx file
#' @param config Configuration list
update_index_hero_image <- function(index_path, config) {
  if (is.null(config$site$logo)) {
    return()  # No logo configured, nothing to update
  }

  content <- readLines(index_path, warn = FALSE)
  content_str <- paste(content, collapse = "\n")

  # Check if hero image already exists
  if (grepl("image:\\s*\\n\\s*file:", content_str)) {
    return()  # Already has hero image
  }

  # Find the hero section and add image after tagline
  # Pattern: find "hero:\n  tagline: ..." and add image after
  hero_image_yaml <- "  image:\n    file: /src/assets/logo.png"

  # Insert image section after tagline line (before actions or other hero content)
  updated <- sub(
    "(hero:\\s*\\n\\s*tagline:[^\\n]*)",
    paste0("\\1\n", hero_image_yaml),
    content_str
  )

  if (updated != content_str) {
    writeLines(updated, index_path)
    cli::cli_alert_success("Updated {.file index.mdx} with hero image")
  }
}

#' Create default index.mdx page
#'
#' @param pkg_path Path to package directory
#' @param output_path Path to output directory
#' @param config Configuration list
create_index_page <- function(pkg_path, output_path, config) {
  index_path <- file.path(output_path, "src", "content", "docs", "index.mdx")

  # If index exists, just update the hero image if needed
 if (file.exists(index_path)) {
    update_index_hero_image(index_path, config)
    return()
  }

  # Get package info
  pkg_name <- get_package_name(pkg_path)
  pkg_desc <- config$site$description %||% "Documentation generated by starlightr"

  # Get hero configuration from YAML
  hero_tagline <- config$home$hero$tagline %||% pkg_desc
  hero_actions <- ""

  if (!is.null(config$home$hero$actions)) {
    actions_yaml <- c()
    for (action in config$home$hero$actions) {
      action_yaml <- sprintf('    - text: %s\n      link: %s\n      icon: %s\n      variant: %s',
                            action$text %||% "Get Started",
                            action$link %||% "/articles/getting-started/",
                            action$icon %||% "right-arrow",
                            action$variant %||% "primary")
      actions_yaml <- c(actions_yaml, action_yaml)
    }
    hero_actions <- paste(actions_yaml, collapse = "\n")
  } else {
    # Default actions
    github_url <- get_github_url(config) %||% "https://github.com/user/repo"
    hero_actions <- sprintf('    - text: Get Started
      link: /articles/getting-started/
      icon: right-arrow
      variant: primary
    - text: View on GitHub
      link: %s
      icon: external
      variant: minimal', github_url)
  }

  # Build hero image section if logo configured

  hero_image <- ""
  if (!is.null(config$site$logo)) {
    hero_image <- "  image:\n    file: /src/assets/logo.png\n"
  }

  # Create default index content with Starlight components
  index_content <- sprintf('---
title: "Welcome to %s"
description: "%s"
template: splash
hero:
  tagline: %s
%s  actions:
%s
---

import { Card, CardGrid } from "@astrojs/starlight/components";

## Quick links

<CardGrid stagger>
  <Card title="Function Reference" icon="list-format">
    Complete API documentation for all functions.
    [Browse Reference >](/reference/)
  </Card>
  <Card title="Articles & Guides" icon="open-book">
    Learn how to use the package with step-by-step guides.
    [Read Articles >](/articles/)
  </Card>
  <Card title="View Source" icon="github">
    Explore the source code and contribute to the project.
    [GitHub Repository >](%s)
  </Card>
  <Card title="Get Help" icon="information">
    Found a bug or need help? Open an issue or discussion.
    [Get Support >](%s/issues)
  </Card>
</CardGrid>
',
    pkg_name,
    pkg_desc,
    hero_tagline,
    hero_image,
    hero_actions,
    get_github_url(config) %||% "https://github.com/user/repo",
    get_github_url(config) %||% "https://github.com/user/repo"
  )

  writeLines(index_content, index_path)
  cli::cli_alert_success("Created {.file index.mdx}")
}

#' Create directory index pages for articles and reference
#'
#' @param pkg_path Path to package directory
#' @param output_path Path to output directory
#' @param config Configuration list
create_directory_indexes <- function(pkg_path, output_path, config) {
  docs_path <- file.path(output_path, "src", "content", "docs")

  # Create articles index only if articles configured
  if (!is.null(config$sidebar$articles)) {
    articles_index_path <- file.path(docs_path, "articles", "index.mdx")
    if (!file.exists(articles_index_path)) {
      pkg_name <- get_package_name(pkg_path)
      articles_content <- sprintf('---
title: "Articles & Guides"
description: "Learn how to use %s with step-by-step guides and tutorials"
---

# Articles & Guides

This section contains guides and tutorials to help you get started with %s and learn about its advanced features.

## Available Articles

Browse the articles in the sidebar to get started!

', pkg_name, pkg_name)

      writeLines(articles_content, articles_index_path)
      cli::cli_alert_success("Created {.file articles/index.mdx}")
    }
  }

  # Create reference index
  reference_index_path <- file.path(docs_path, "reference", "index.mdx")
  if (!file.exists(reference_index_path)) {
    pkg_name <- get_package_name(pkg_path)
    reference_content <- sprintf('---
title: "Function Reference"
description: "Complete API documentation for all %s functions"
---

# Function Reference

This section contains detailed documentation for all functions in the %s package.

## Available Functions

Browse the functions in the sidebar to explore the complete API documentation.

', pkg_name, pkg_name)

    writeLines(reference_content, reference_index_path)
    cli::cli_alert_success("Created {.file reference/index.mdx}")
  }
}

#' Copy assets from package to site
#'
#' @param pkg_path Path to package directory
#' @param output_path Path to output directory
#' @param config Configuration list
copy_assets <- function(pkg_path, output_path, config) {
  # Copy common assets if they exist
  assets_to_check <- c(
    "vignettes/assets",
    "vignettes/public",
    "man/figures"
  )

  public_dir <- file.path(output_path, "public")

  for (asset_path in assets_to_check) {
    full_path <- file.path(pkg_path, asset_path)
    if (dir.exists(full_path)) {
      file.copy(full_path, public_dir, recursive = TRUE)
      cli::cli_alert_success("Copied assets from {.path {asset_path}}")
    }
  }
}

#' Copy logo and favicon to site
#'
#' @param pkg_path Path to package directory
#' @param output_path Path to output directory
#' @param config Configuration list
copy_branding_assets <- function(pkg_path, output_path, config) {
  # Copy logo to src/assets/ (Astro imports this as a module)
  if (!is.null(config$site$logo)) {
    logo_src <- file.path(pkg_path, config$site$logo)
    if (file.exists(logo_src)) {
      assets_dir <- file.path(output_path, "src", "assets")
      if (!dir.exists(assets_dir)) dir.create(assets_dir, recursive = TRUE)
      file.copy(logo_src, file.path(assets_dir, "logo.png"), overwrite = TRUE)
      cli::cli_alert_success("Copied logo to {.path src/assets/}")
    } else {
      cli::cli_warn("Logo file not found: {.path {logo_src}}")
    }
  }

  # Copy favicon to public/images/ (served as static file)
  if (!is.null(config$site$favicon)) {
    favicon_src <- file.path(pkg_path, config$site$favicon)
    if (file.exists(favicon_src)) {
      images_dir <- file.path(output_path, "public", "images")
      if (!dir.exists(images_dir)) dir.create(images_dir, recursive = TRUE)
      file.copy(favicon_src, file.path(images_dir, "favicon.png"), overwrite = TRUE)
      cli::cli_alert_success("Copied favicon to {.path public/images/}")
    } else {
      cli::cli_warn("Favicon file not found: {.path {favicon_src}}")
    }
  }
}

#' Preview the generated site
#'
#' @param output_path Path to built site
preview_site <- function(output_path) {
  cli::cli_h2("To preview your site")
  cli::cli_ol(c(
    "cd {.path {output_path}}",
    "npm install",
    "npm run dev"
  ))
}

# Utility function for null-or-default assignment
`%||%` <- function(a, b) if (is.null(a)) b else a

#' Expand pkgdown selector functions to actual function names
#'
#' @param contents Vector of function names and selectors
#' @param output_path Path to output directory to find available functions
#'
#' @return Vector with selectors expanded to actual function names
expand_pkgdown_selectors <- function(contents, output_path = NULL) {
  if (is.null(contents) || length(contents) == 0) {
    return(character(0))
  }

  # Get all available functions from the reference directory
  available_functions <- character(0)
  if (!is.null(output_path)) {
    ref_dir <- file.path(output_path, "src", "content", "docs", "reference")
    if (dir.exists(ref_dir)) {
      ref_files <- list.files(ref_dir, pattern = "\\.mdx?$", full.names = FALSE)
      available_functions <- tools::file_path_sans_ext(ref_files)
    }
  }

  expanded <- character(0)

  for (content in contents) {
    # Check if this is a selector function
    if (is_pkgdown_selector(content)) {
      # Expand the selector
      matches <- expand_selector(content, available_functions)
      expanded <- c(expanded, matches)
    } else {
      # Keep as-is
      expanded <- c(expanded, content)
    }
  }

  # Remove duplicates and return
  unique(expanded)
}

#' Check if a string is a pkgdown selector function
#'
#' @param content String to check
#'
#' @return Logical indicating if it's a selector
is_pkgdown_selector <- function(content) {
  grepl("^(starts_with|ends_with|contains|matches)\\s*\\(", content)
}

#' Expand a single selector to matching function names
#'
#' @param selector Selector string like 'ends_with("_at")'
#' @param available_functions Vector of available function names
#'
#' @return Vector of matching function names
expand_selector <- function(selector, available_functions) {
  if (length(available_functions) == 0) {
    return(character(0))
  }

  # Extract the selector type and pattern
  if (grepl("^starts_with\\s*\\(", selector)) {
    pattern <- extract_quoted_pattern(selector)
    if (!is.null(pattern)) {
      regex <- paste0("^", escape_regex(pattern))
      return(available_functions[grepl(regex, available_functions)])
    }
  } else if (grepl("^ends_with\\s*\\(", selector)) {
    pattern <- extract_quoted_pattern(selector)
    if (!is.null(pattern)) {
      regex <- paste0(escape_regex(pattern), "$")
      return(available_functions[grepl(regex, available_functions)])
    }
  } else if (grepl("^contains\\s*\\(", selector)) {
    pattern <- extract_quoted_pattern(selector)
    if (!is.null(pattern)) {
      regex <- escape_regex(pattern)
      return(available_functions[grepl(regex, available_functions)])
    }
  } else if (grepl("^matches\\s*\\(", selector)) {
    pattern <- extract_quoted_pattern(selector)
    if (!is.null(pattern)) {
      # For matches, use the pattern as-is (it's already a regex)
      return(available_functions[grepl(pattern, available_functions)])
    }
  }

  # If we can't parse the selector, return empty
  character(0)
}

#' Extract the quoted pattern from a selector function
#'
#' @param selector Selector string like 'ends_with("_at")'
#'
#' @return The extracted pattern or NULL if not found
extract_quoted_pattern <- function(selector) {
  # Match patterns like: ends_with("pattern") or ends_with('pattern')
  matches <- regexec('\\(\\s*["\']([^"\']+)["\']\\s*\\)', selector)
  if (matches[[1]][1] != -1) {
    captures <- regmatches(selector, matches)[[1]]
    if (length(captures) >= 2) {
      return(captures[2])
    }
  }
  return(NULL)
}

#' Escape special regex characters in a pattern
#'
#' @param pattern String to escape
#'
#' @return Escaped string
escape_regex <- function(pattern) {
  gsub("([.^$*+?{}\\[\\]\\(\\)|\\\\])", "\\\\\\1", pattern)
}

#' Find the actual documentation file for a function using Rd database
#'
#' Handles @rdname cases where functions are documented in different files
#'
#' @param function_name Name of the function to find
#' @param pkg_name Package name (for accessing Rd database)
#'
#' @return The base name of the Rd file containing the function's documentation, or NULL
find_function_doc_file <- function(function_name, pkg_name) {
  if (is.null(function_name) || is.null(pkg_name) || nchar(function_name) == 0) {
    return(NULL)
  }

  tryCatch({
    # Get the Rd database for the package
    rd_db <- tools::Rd_db(pkg_name)

    # Search through all Rd files for the function
    for (rd_file_name in names(rd_db)) {
      rd_obj <- rd_db[[rd_file_name]]

      # Check if this Rd object documents the function we're looking for
      if (rd_contains_function(rd_obj, function_name)) {
        # Return the base name without .Rd extension
        return(tools::file_path_sans_ext(rd_file_name))
      }
    }

    return(NULL)
  }, error = function(e) {
    # If we can't access Rd database, return NULL
    return(NULL)
  })
}

#' Check if an Rd object contains documentation for a specific function
#'
#' @param rd_obj Rd object from tools::Rd_db
#' @param function_name Function name to look for
#'
#' @return Logical indicating if the function is documented in this Rd object
rd_contains_function <- function(rd_obj, function_name) {
  # Check the \name section first
  name_section <- get_rd_section(rd_obj, "name")
  if (!is.null(name_section)) {
    name_text <- trimws(paste(unlist(name_section), collapse = ""))
    if (name_text == function_name) {
      return(TRUE)
    }
  }

  # Check \alias sections (functions documented via @rdname appear as aliases)
  aliases <- character()
  for (element in rd_obj) {
    el_tag <- attr(element, "Rd_tag")
    if (!is.null(el_tag) && el_tag == "\\alias") {
      alias_content <- paste(unlist(element), collapse = "")
      alias_content <- trimws(alias_content)
      aliases <- c(aliases, alias_content)
    }
  }

  # Check if our function is in the aliases
  return(function_name %in% aliases)
}


#' Check if a path is absolute
#'
#' @param path Character string representing a file path
#' @return Logical indicating if the path is absolute
is_absolute_path <- function(path) {
  # Check for Unix-style absolute paths (starting with /)
  if (grepl("^/", path)) return(TRUE)

  # Check for Windows-style absolute paths (C:\ or \\)
  if (grepl("^[A-Za-z]:", path) || grepl("^\\\\", path)) return(TRUE)

  # Check for tilde expansion (~)
  if (grepl("^~", path)) return(TRUE)

  return(FALSE)
}

#' Get package name from DESCRIPTION file
#'
#' @param pkg_path Path to package directory
#' @return Package name as string
get_package_name <- function(pkg_path) {
  desc_path <- file.path(pkg_path, "DESCRIPTION")

  if (!file.exists(desc_path)) {
    stop("DESCRIPTION file not found in: ", pkg_path)
  }

  desc_lines <- readLines(desc_path)
  name_line <- grep("^Package:", desc_lines, value = TRUE)

  if (length(name_line) == 0) {
    stop("Package name not found in DESCRIPTION file")
  }

  pkg_name <- trimws(sub("^Package:\\s*", "", name_line[1]))
  return(pkg_name)
}

#' Initialize starlightr for a package
#'
#' Sets up the necessary files and configuration for using starlightr.
#' Creates a default _starlightr.yaml configuration file, updates .Rbuildignore,
#' and creates the vignettes/ directory structure.
#'
#' @param pkg Path to package directory, defaults to current directory
#' @param open Logical, whether to open the configuration file for editing
#'
#' @return Invisibly returns TRUE if successful
#' @export
#'
#' @examples \dontrun{
#' # Initialize starlightr for current package
#' use_starlightr()
#'
#' # Initialize for a specific package
#' use_starlightr("/path/to/my/package")
#' }
use_starlightr <- function(pkg = ".", open = interactive()) {
  # Resolve package path
  pkg_path <- normalizePath(pkg, mustWork = TRUE)

  cli::cli_h1("Setting up starlightr for {.pkg {basename(pkg_path)}}")

  # Create _starlightr.yaml if it doesn't exist
  config_path <- file.path(pkg_path, "_starlightr.yaml")
  if (!file.exists(config_path)) {
    create_default_config(config_path, pkg_path)
    cli::cli_alert_success("Created _starlightr.yaml")
  } else {
    cli::cli_alert_info("_starlightr.yaml already exists")
  }

  # Update .Rbuildignore
  update_rbuildignore(pkg_path)

  # Create vignettes directory
  articles_dir <- file.path(pkg_path, "vignettes")
  if (!dir.exists(articles_dir)) {
    dir.create(articles_dir, recursive = TRUE)

    # Create a sample article
    create_sample_article(articles_dir)
    cli::cli_alert_success("Created vignettes/ directory with sample article")
  } else {
    cli::cli_alert_info("vignettes/ directory already exists")
  }

  cli::cli_alert_success("starlightr setup complete!")
  cli::cli_bullets(c(
    "*" = "Edit {.file _starlightr.yaml} to customize your site",
    "*" = "Add {.file .Rmd} files to {.path vignettes/} for articles",
    "*" = "Run {.fn build_site} to generate your documentation"
  ))

  if (open && file.exists(config_path)) {
    utils::file.edit(config_path)
  }

  invisible(TRUE)
}

#' Create default _starlightr.yaml configuration
#'
#' @param config_path Path where to create the config file
#' @param pkg_path Path to package directory
create_default_config <- function(config_path, pkg_path) {
  # Try to read DESCRIPTION to get package info
  desc_path <- file.path(pkg_path, "DESCRIPTION")
  pkg_name <- basename(pkg_path)
  pkg_desc <- "Documentation generated by starlightr"

  if (file.exists(desc_path)) {
    tryCatch({
      desc_lines <- readLines(desc_path)

      # Extract package name
      name_line <- grep("^Package:", desc_lines, value = TRUE)
      if (length(name_line) > 0) {
        pkg_name <- trimws(sub("^Package:\\s*", "", name_line[1]))
      }

      # Extract description
      desc_line <- grep("^Description:", desc_lines, value = TRUE)
      if (length(desc_line) > 0) {
        pkg_desc <- trimws(sub("^Description:\\s*", "", desc_line[1]))
      }
    }, error = function(e) {
      # Use defaults if can't read DESCRIPTION
    })
  }

  config_content <- sprintf('# starlightr configuration file
# This file defines how your R package documentation will be built into a Starlight site

# Site metadata
site:
  title: "%s"
  description: "%s"
  # logo: "man/figures/logo.png"       # Path to logo image (relative to package root)
  # favicon: "man/figures/favicon.png" # Path to favicon (can be same as logo)

# Home page configuration
home:
  hero:
    tagline: "%s"
    actions:
      - text: "Get Started"
        link: "/articles/getting-started/"
        icon: "right-arrow"
        variant: "primary"
      - text: "View on GitHub"
        link: "https://github.com/user/repo"  # Update this!
        icon: "external"
        variant: "minimal"

# Sidebar configuration for different sections
sidebar:
  articles:
    # Custom organization of vignettes/articles
    - title: "Getting Started"
      contents:
        - "introduction"
        - "getting-started"
    # Example of collapsed group:
    # - title: "Advanced Topics"
    #   collapsed: true
    #   contents:
    #     - "advanced-usage"
    #     - "customization"

  reference:
    # Organize functions into groups
    - title: "Site Building"
      contents:
        - "build_site"
        - "use_starlightr"
    - title: "Documentation Processing"
      collapsed: true  # Start this group collapsed
      contents:
        - "extract_*"  # Functions matching pattern will use autogenerate
        - "process_*"
        - "get_rd_tags"
    - title: "Formatting & Output"
      collapsed: true  # Start this group collapsed
      contents:
        - "format_*"
        - "write_*"
        - "clean_text"

# Theme and appearance
theme:
  color_mode: "auto"  # light, dark, or auto

# Content processing options
content:
  # Custom sections to format as code
  code_sections:
    - "usage"
    - "examples"

  # Sections to skip entirely
  skip_sections:
    - "seealso"
    - "name"

# Output directory for generated site
output:
  dir: "../%s-docs"  # External directory (recommended)
  # dir: "docs"       # Internal directory (not recommended due to bloat)
  include_build_files: true
', pkg_name, pkg_desc, pkg_desc, pkg_name)

  writeLines(config_content, config_path)

  # Ensure file ends with newline to avoid warnings
  cat("\n", file = config_path, append = TRUE)
}

#' Update .Rbuildignore to include _starlightr.yaml
#'
#' @param pkg_path Path to package directory
update_rbuildignore <- function(pkg_path) {
  rbuildignore_path <- file.path(pkg_path, ".Rbuildignore")

  # Create .Rbuildignore if it doesn't exist
  if (!file.exists(rbuildignore_path)) {
    writeLines("^_starlightr\\.yaml$", rbuildignore_path)
    cli::cli_alert_success("Created .Rbuildignore with _starlightr.yaml")
    return()
  }

  # Read existing .Rbuildignore
  existing_lines <- readLines(rbuildignore_path)

  # Check if _starlightr.yaml is already ignored
  pattern_exists <- any(grepl("_starlightr", existing_lines, fixed = TRUE))

  if (!pattern_exists) {
    # Add the pattern
    updated_lines <- c(existing_lines, "^_starlightr\\.yaml$")
    writeLines(updated_lines, rbuildignore_path)
    cli::cli_alert_success("Updated .Rbuildignore to include _starlightr.yaml")
  } else {
    cli::cli_alert_info(".Rbuildignore already includes _starlightr.yaml pattern")
  }
}

#' Create a sample article in vignettes/
#'
#' @param articles_dir Path to vignettes directory
create_sample_article <- function(articles_dir) {
  sample_content <- '---
title: "Getting Started"
description: "Introduction to using this package"
---

# Getting Started

This is a sample article created by starlightr.

## Installation

You can install this package from GitHub:

```r
# Install from GitHub
devtools::install_github("user/repo")
```

## Basic Usage

Here\'s how to use the main functions:

```r
library(packagename)

# Example usage
result <- main_function()
```

## Next Steps

- Edit this file to add your own content
- Create additional .Rmd files in vignettes/
- Run `starlightr::build_site()` to generate your documentation site
'

  sample_path <- file.path(articles_dir, "getting-started.Rmd")
  writeLines(sample_content, sample_path)

  # Also create an introduction article as backup
  intro_content <- '---
title: "Introduction"
description: "Introduction to using this package"
---

# Introduction

Welcome to the package documentation!

## Overview

This package provides tools for [describe main functionality].

## Quick Start

Here\'s a simple example to get you started:

```r
library(packagename)

# Your first example
result <- main_function()
```

## Next Steps

- Browse the [Function Reference](/reference/) for detailed API documentation
- Check out more [Articles & Guides](/articles/) for advanced usage
'

  intro_path <- file.path(articles_dir, "introduction.Rmd")
  if (!file.exists(intro_path)) {
    writeLines(intro_content, intro_path)
  }
}