# Configuration handling for starlightr

#' Read and parse starlightr configuration
#'
#' @param config_path Path to the _starlightr.toml file
#'
#' @return List containing parsed configuration
#' @keywords internal
read_config <- function(config_path) {
  if (!file.exists(config_path)) {
    cli::cli_alert_info("No _starlightr.toml found, using default configuration")
    cli::cli_alert("Tip: Run {.fn use_starlightr} to create a configuration file")
    return(default_config())
  }

  tryCatch({
    # Use shared helper from config_helpers.R
    config <- read_config_toml(config_path)

    # Merge with defaults to ensure all required fields exist
    merge_config(config, default_config())
  }, error = function(e) {
    stop("Error reading configuration file: ", e$message)
  })
}

#' Get default configuration
#'
#' @return List with default configuration values
#' @keywords internal
default_config <- function() {
  list(
    site = list(
      title = "Package Documentation",
      description = "Documentation generated by starlightr"
    ),
    navbar = list(
      left = list(
        list(text = "Home", href = "index.md"),
        list(text = "Reference", href = "reference/"),
        list(text = "Articles", href = "articles/")
      )
    ),
    theme = list(
      color_mode = "auto"
    ),
    content = list(
      code_sections = c("usage", "examples"),
      skip_sections = c("name", "alias", "title")
    ),
    output = list(
      dir = "docs",
      include_build_files = TRUE
    ),
    versions = list(
      enabled = FALSE
    )
  )
}

#' Merge user config with defaults
#'
#' @param user_config User-provided configuration
#' @param default_config Default configuration
#'
#' @return Merged configuration list
#' @keywords internal
merge_config <- function(user_config, default_config) {
  # Simple recursive merge - in production we'd want something more sophisticated
  utils::modifyList(default_config, user_config)
}
