# Generated by extendr: Do not edit by hand
# nolint start

#' @usage NULL
#' @useDynLib starlightr, .registration = TRUE
NULL

#' render_reference
#'
#' Renders an .Rd file to an mdx file.
#'
#' @param rd_file path to Rd file to convert to .mdx
#' @param output_dir path to directory where reference mdx files are saved
#' @param config_file path to _starlightr.toml
#'
#' @return NULL
#' @export
#'
#' @examples \dontrun{
#' render_reference(
#'   rd_file = "man/function.Rd",
#'   output_dir = "../Docs/pkg-docs/src/content/docs/reference",
#'   config_file = "_starlightr.toml"
#' )
#' }
render_reference <- function(rd_file, output_dir, config_file = '_starlightr.toml', external_links_file = NULL, example_outputs_file = NULL) .Call(wrap__render_reference, rd_file, output_dir, config_file, external_links_file, example_outputs_file)

render_references <- function(rd_dir, output_dir, config_file = '_starlightr.toml', external_links_file = NULL, example_outputs_file = NULL) .Call(wrap__render_references, rd_dir, output_dir, config_file, external_links_file, example_outputs_file)

# nolint end
