# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_starlightr_wrappers", use_symbols = TRUE, package_name = "starlightr")

#' @usage NULL
#' @useDynLib starlightr, .registration = TRUE
NULL


# nolint end
