# Generated by extendr: Do not edit by hand
# nolint start

#' @usage NULL
#' @useDynLib starlightr, .registration = TRUE
NULL

#' render_reference
#'
#' Renders an .Rd file to an mdx file.
#'
#' @param rd_file path to Rd file to convert to .mdx
#' @param output_file path to new mdx file
#' @param config_file path to _starlightr.toml
#'
#' @return NULL
#' @export
#'
#' @examples \dontrun{
#' render_reference(
#'   rd_file = "man/function.Rd",
#'   output_file = "../Docs/src/content/docs/reference/function.mdx",
#'   config_file = "_starlightr.toml"
#' )
#' }
render_reference <- function(rd_file, output_file, config_file = '_starlightr.toml') .Call(wrap__render_reference, rd_file, output_file, config_file)

# nolint end
