# Page creation helpers for starlightr

#' Inject a hero image into an existing index.mdx
#'
#' Parses the YAML frontmatter and adds the logo as the hero image if one
#' isn't already set, leaving the body untouched. Used to retrofit a logo
#' onto an existing index.mdx without overwriting it.
#'
#' @param index_path Path to index.mdx file
#' @param config Configuration list
#' @noRd
update_index_hero_image <- function(index_path, config) {
  if (is.null(config$site$logo)) {
    return() # No logo configured, nothing to do
  }

  lines <- readLines(index_path, warn = FALSE)

  # Frontmatter is the block between the first two "---" fences.
  fences <- which(lines == "---")
  if (length(fences) < 2) {
    return() # No frontmatter block to update
  }
  fm_str <- paste(lines[(fences[1] + 1):(fences[2] - 1)], collapse = "\n")
  body <- if (fences[2] < length(lines)) {
    lines[(fences[2] + 1):length(lines)]
  } else {
    character()
  }

  fm <- yaml::yaml.load(fm_str)
  if (!is.null(fm$hero$image$file)) {
    return() # Already has a hero image
  }

  fm$hero$image <- list(file = "../../assets/logo.png")

  # verbatim_logical writes true/false, not yaml's default yes/no (which Astro
  # would read as a string and reject against Starlight's boolean schema).
  new_fm <- sub(
    "\n$",
    "",
    yaml::as.yaml(fm, handlers = list(logical = yaml::verbatim_logical))
  )
  writeLines(c("---", new_fm, "---", body), index_path)
  cli::cli_alert_success("Added hero image to {.file index.mdx}")
}

#' Create default index.mdx page
#'
#' @param pkg_path Path to package directory
#' @param output_path Path to output directory
#' @param config Configuration list
#' @param overwrite Logical, whether to overwrite existing index.mdx
#' @keywords internal
#' @noRd
create_index_page <- function(
  pkg_path,
  output_path,
  config,
  overwrite = FALSE
) {
  index_path <- file.path(output_path, "src", "content", "docs", "index.mdx")
  file_existed <- file.exists(index_path)

  # index.mdx is user-editable, so don't overwrite an existing one; just
  # retrofit the hero image if a logo was added since it was created.
  if (file_existed && !overwrite) {
    update_index_hero_image(index_path, config)
    return()
  }

  # Get package info
  pkg_name <- get_package_name(pkg_path)
  pkg_desc <- config$site$description %||%
    "Documentation generated by starlightr"

  # Get hero configuration from YAML
  hero_tagline <- config$home$hero$tagline %||% pkg_desc
  hero_actions <- ""

  if (!is.null(config$home$hero$actions)) {
    actions_yaml <- c()
    for (action in config$home$hero$actions) {
      # Escape embedded quotes in text/link values for YAML safety
      action_text <- gsub(
        '"',
        '\\"',
        action$text %||% "Get Started",
        fixed = TRUE
      )
      action_link <- gsub(
        '"',
        '\\"',
        action$link %||% "/articles/getting-started/",
        fixed = TRUE
      )
      action_yaml <- sprintf(
        '    - text: "%s"\n      link: "%s"\n      icon: %s\n      variant: %s',
        action_text,
        action_link,
        action$icon %||% "right-arrow",
        action$variant %||% "primary"
      )
      actions_yaml <- c(actions_yaml, action_yaml)
    }
    hero_actions <- paste(actions_yaml, collapse = "\n")
  } else {
    # Default actions
    github_url <- get_github_url(config) %||% "https://github.com/user/repo"
    hero_actions <- sprintf(
      '    - text: Get Started
      link: /articles/getting-started/
      icon: right-arrow
      variant: primary
    - text: View on GitHub
      link: %s
      icon: external
      variant: minimal',
      github_url
    )
  }

  # Build cards section if configured
  cards_content <- ""
  if (!is.null(config$home$cards) && length(config$home$cards) > 0) {
    card_items <- vapply(
      config$home$cards,
      function(card) {
        icon_attr <- if (!is.null(card$icon))
          sprintf(' icon="%s"', card$icon) else ""
        sprintf(
          '  <Card title="%s"%s>\n    %s\n    [Learn more >](%s)\n  </Card>',
          card$title %||% "Untitled",
          icon_attr,
          card$description %||% "",
          card$link %||% "/"
        )
      },
      character(1)
    )

    cards_content <- sprintf(
      '
import { Card, CardGrid } from "@astrojs/starlight/components";

## Quick links

<CardGrid stagger>
%s
</CardGrid>
',
      paste(card_items, collapse = "\n")
    )
  }

  # Create default index content with Starlight components
  site_title <- config$site$title %||% pkg_name
  hero_tagline_escaped <- escape_quoted_string(hero_tagline)
  pkg_desc_escaped <- escape_quoted_string(pkg_desc)

  data <- list(
    title = site_title,
    description = pkg_desc_escaped,
    tagline = hero_tagline_escaped,
    has_hero_image = !is.null(config$site$logo),
    hero_actions = hero_actions,
    cards_content = cards_content
  )

  index_content <- render_template("index.mdx", data)

  writeLines(index_content, index_path)
  if (file_existed) {
    cli::cli_alert_success("Overwrote {.file index.mdx}")
  } else {
    cli::cli_alert_success("Created {.file index.mdx}")
  }
}
