# Page creation helpers for starlightr

#' Update hero image in existing index.mdx
#'
#' @param index_path Path to index.mdx file
#' @param config Configuration list
#' @keywords internal
update_index_hero_image <- function(index_path, config) {
  if (is.null(config$site$logo)) {
    return()  # No logo configured, nothing to update
  }

  content <- readLines(index_path, warn = FALSE)
  content_str <- paste(content, collapse = "\n")

  # Check if hero image already exists
  if (grepl("image:\\s*\\n\\s*file:", content_str)) {
    return()  # Already has hero image
  }

  # Find the hero section and add image after tagline
  # Pattern: find "hero:\n  tagline: ..." and add image after
  hero_image_yaml <- "  image:\n    file: /src/assets/logo.png"

  # Insert image section after tagline line (before actions or other hero content)
  updated <- sub(
    "(hero:\\s*\\n\\s*tagline:[^\\n]*)",
    paste0("\\1\n", hero_image_yaml),
    content_str
  )

  if (updated != content_str) {
    writeLines(updated, index_path)
    cli::cli_alert_success("Updated {.file index.mdx} with hero image")
  }
}

#' Create default index.mdx page
#'
#' @param pkg_path Path to package directory
#' @param output_path Path to output directory
#' @param config Configuration list
#' @keywords internal
create_index_page <- function(pkg_path, output_path, config) {
  index_path <- file.path(output_path, "src", "content", "docs", "index.mdx")

  # If index exists, just update the hero image if needed
  if (file.exists(index_path)) {
    update_index_hero_image(index_path, config)
    return()
  }

  # Get package info
  pkg_name <- get_package_name(pkg_path)
  pkg_desc <- config$site$description %||% "Documentation generated by starlightr"

  # Get hero configuration from YAML
  hero_tagline <- config$home$hero$tagline %||% pkg_desc
  hero_actions <- ""

  if (!is.null(config$home$hero$actions)) {
    actions_yaml <- c()
    for (action in config$home$hero$actions) {
      action_yaml <- sprintf('    - text: %s\n      link: %s\n      icon: %s\n      variant: %s',
                            action$text %||% "Get Started",
                            action$link %||% "/articles/getting-started/",
                            action$icon %||% "right-arrow",
                            action$variant %||% "primary")
      actions_yaml <- c(actions_yaml, action_yaml)
    }
    hero_actions <- paste(actions_yaml, collapse = "\n")
  } else {
    # Default actions
    github_url <- get_github_url(config) %||% "https://github.com/user/repo"
    hero_actions <- sprintf('    - text: Get Started
      link: /articles/getting-started/
      icon: right-arrow
      variant: primary
    - text: View on GitHub
      link: %s
      icon: external
      variant: minimal', github_url)
  }

  # Build hero image section if logo configured
  hero_image <- ""
  if (!is.null(config$site$logo)) {
    hero_image <- "  image:\n    file: /src/assets/logo.png\n"
  }

  # Build cards section if configured
  cards_content <- ""
  if (!is.null(config$home$cards) && length(config$home$cards) > 0) {
    card_items <- vapply(config$home$cards, function(card) {
      icon_attr <- if (!is.null(card$icon)) sprintf(' icon="%s"', card$icon) else ""
      sprintf('  <Card title="%s"%s>\n    %s\n    [Learn more >](%s)\n  </Card>',
              card$title %||% "Untitled",
              icon_attr,
              card$description %||% "",
              card$link %||% "/")
    }, character(1))

    cards_content <- sprintf('
import { Card, CardGrid } from "@astrojs/starlight/components";

## Quick links

<CardGrid stagger>
%s
</CardGrid>
', paste(card_items, collapse = "\n"))
  }

  # Create default index content with Starlight components
  index_content <- sprintf('---
title: "Welcome to %s"
description: "%s"
template: splash
pagefind: true
hero:
  tagline: %s
%s  actions:
%s
---%s',
    pkg_name,
    pkg_desc,
    hero_tagline,
    hero_image,
    hero_actions,
    cards_content
  )

  writeLines(index_content, index_path)
  cli::cli_alert_success("Created {.file index.mdx}")
}
