#' Convert pkgdown YAML configuration to starlightr YAML
#'
#' This function reads a pkgdown _pkgdown.yml file and converts it to the
#' starlightr YAML format, handling the title/subtitle structure for references
#' and articles.
#'
#' @param pkgdown_file Path to pkgdown YAML file (default: "_pkgdown.yml")
#' @param output_file Path for output starlightr YAML file (default: "_starlightr.yaml")
#' @param pkg_path Path to package directory (default: ".")
#'
#' @return List with conversion results and any warnings
#' @export
#'
#' @examples \dontrun{
#' # Convert pkgdown config to starlightr
#' pkgdown_to_starlight()
#'
#' # Specify custom paths
#' pkgdown_to_starlight("my_pkgdown.yml", "my_starlightr.yaml")
#' }
pkgdown_to_starlight <- function(pkgdown_file = "_pkgdown.yml",
                                output_file = "_starlightr.yaml",
                                pkg_path = ".") {

  # Check if pkgdown file exists
  if (!file.exists(file.path(pkg_path, pkgdown_file))) {
    stop("pkgdown file not found: ", file.path(pkg_path, pkgdown_file))
  }

  # Parse pkgdown YAML
  pkgdown <- yaml::yaml.load_file(file.path(pkg_path, pkgdown_file))

  # Extract basic site information
  site_info <- extract_site_info(pkgdown, pkg_path)

  # Convert reference structure
  reference_structure <- convert_reference_structure(pkgdown$reference)

  # Convert articles structure
  articles_structure <- convert_articles_structure(pkgdown$articles)

  # Build starlightr configuration
  starlightr_config <- list(
    site = site_info$site,
    home = site_info$home,
    sidebar = list(
      reference = reference_structure,
      articles = articles_structure
    ),
    content = list(
      code_sections = c("usage", "examples"),
      skip_sections = c("name", "seealso")
    ),
    theme = list(
      color_mode = "auto"
    ),
    output = list(
      dir = "docs",
      include_build_files = TRUE
    )
  )

  # Write the converted YAML
  output_path <- file.path(pkg_path, output_file)
  yaml::write_yaml(starlightr_config, output_path)

  # Return conversion report
  list(
    success = TRUE,
    output_file = output_path,
    warnings = character(),
    message = paste("Successfully converted", pkgdown_file, "to", output_file)
  )
}

#' Extract site information from pkgdown config
#'
#' @param pkgdown Parsed pkgdown YAML
#' @param pkg_path Path to package directory
#'
#' @return List with site and home information
extract_site_info <- function(pkgdown, pkg_path) {

  # Get package name from DESCRIPTION if available
  pkg_name <- tryCatch({
    desc_path <- file.path(pkg_path, "DESCRIPTION")
    if (file.exists(desc_path)) {
      desc_lines <- readLines(desc_path)
      name_line <- grep("^Package:", desc_lines, value = TRUE)
      if (length(name_line) > 0) {
        trimws(sub("^Package:\\s*", "", name_line[1]))
      } else {
        basename(normalizePath(pkg_path))
      }
    } else {
      basename(normalizePath(pkg_path))
    }
  }, error = function(e) basename(normalizePath(pkg_path)))

  # Extract title and description
  title <- pkgdown$home$title %||%
           pkgdown$title %||%
           paste(pkg_name, "Documentation")

  description <- pkgdown$home$description %||%
                pkgdown$home$desc %||%
                pkgdown$description %||%
                "Documentation generated by starlightr"

  # Extract GitHub URL
  github_url <- extract_github_url(pkgdown)

  # Build site config
  site <- list(
    title = title,
    description = description
  )

  # Build home config with hero
  home <- list(
    hero = list(
      tagline = description,
      actions = build_hero_actions(github_url)
    )
  )

  list(site = site, home = home)
}

#' Extract GitHub URL from various pkgdown locations
#'
#' @param pkgdown Parsed pkgdown YAML
#'
#' @return GitHub URL or NULL
extract_github_url <- function(pkgdown) {

  # Check URL field first
  if (!is.null(pkgdown$url) && grepl("github", pkgdown$url, ignore.case = TRUE)) {
    # Convert GitHub Pages URL to repo URL
    return(gsub("\\.github\\.io/([^/]+)/?$", "/\\1", pkgdown$url))
  }

  # Check navbar right section
  if (!is.null(pkgdown$navbar$right)) {
    for (item in pkgdown$navbar$right) {
      if (!is.null(item$icon) && item$icon == "github") {
        return(item$href)
      }
      if (!is.null(item$href) && grepl("github\\.com", item$href)) {
        return(item$href)
      }
    }
  }

  # Check development section
  if (!is.null(pkgdown$development$source_url)) {
    return(pkgdown$development$source_url)
  }

  return(NULL)
}

#' Build hero actions for starlightr
#'
#' @param github_url GitHub repository URL
#'
#' @return List of hero actions
build_hero_actions <- function(github_url = NULL) {
  actions <- list(
    list(
      text = "Get Started",
      link = "/articles/",
      icon = "right-arrow",
      variant = "primary"
    )
  )

  if (!is.null(github_url)) {
    actions[[length(actions) + 1]] <- list(
      text = "View on GitHub",
      link = github_url,
      icon = "external",
      variant = "minimal"
    )
  }

  actions
}

#' Convert pkgdown reference structure to starlightr format
#'
#' @param reference Pkgdown reference section
#'
#' @return Starlightr reference structure
convert_reference_structure <- function(reference) {

  if (is.null(reference) || length(reference) == 0) {
    # Default fallback
    return(list(
      list(
        label = "Reference",
        autogenerate = list(directory = "reference")
      )
    ))
  }

  result <- list()
  current_section <- NULL
  current_items <- list()

  for (item in reference) {

    # If this item has a title, it starts a new main section
    if (!is.null(item$title)) {

      # Save previous section if it exists
      if (!is.null(current_section)) {
        if (length(current_items) > 0) {
          current_section$items <- current_items
        }
        result[[length(result) + 1]] <- current_section
      }

      # Start new section
      current_section <- list(
        label = item$title
      )

      # Add description if available
      if (!is.null(item$desc)) {
        current_section$desc <- item$desc
      }

      # If this title item has contents directly, add them
      if (!is.null(item$contents)) {
        current_section$contents <- item$contents
      }

      current_items <- list()
    }

    # If this item has a subtitle, it's a subsection
    else if (!is.null(item$subtitle)) {

      if (is.null(current_section)) {
        # No current section, create a default one
        current_section <- list(label = "Reference")
      }

      subsection <- list(
        label = item$subtitle,
        contents = item$contents %||% character()
      )

      # Add description if available
      if (!is.null(item$desc)) {
        subsection$desc <- item$desc
      }

      current_items[[length(current_items) + 1]] <- subsection
    }
  }

  # Don't forget the last section
  if (!is.null(current_section)) {
    if (length(current_items) > 0) {
      current_section$items <- current_items
    }
    result[[length(result) + 1]] <- current_section
  }

  # If no sections were created, add default
  if (length(result) == 0) {
    result <- list(
      list(
        label = "Reference",
        autogenerate = list(directory = "reference")
      )
    )
  }

  result
}

#' Convert pkgdown articles structure to starlightr format
#'
#' @param articles Pkgdown articles section
#'
#' @return Starlightr articles structure
convert_articles_structure <- function(articles) {

  if (is.null(articles) || length(articles) == 0) {
    # Default fallback
    return(list(
      list(
        label = "Articles",
        autogenerate = list(directory = "articles")
      )
    ))
  }

  result <- list()

  for (item in articles) {

    if (!is.null(item$title)) {

      section <- list(
        label = item$title
      )

      # Add description if available
      if (!is.null(item$desc)) {
        section$desc <- item$desc
      }

      # Add contents if available
      if (!is.null(item$contents)) {
        section$contents <- item$contents
      } else {
        # Use autogenerate if no specific contents
        section$autogenerate <- list(directory = "articles")
      }

      result[[length(result) + 1]] <- section
    }
  }

  # If no sections were created, add default
  if (length(result) == 0) {
    result <- list(
      list(
        label = "Articles",
        autogenerate = list(directory = "articles")
      )
    )
  }

  result
}

# Utility function for null-or-default assignment
`%||%` <- function(a, b) if (is.null(a)) b else a