# Setup and initialization functions for starlightr

#' Initialize starlightr for a package
#'
#' Sets up the necessary files and configuration for using starlightr.
#' Creates a default _starlightr.toml configuration file and updates .Rbuildignore.
#'
#' @param pkg Path to package directory, defaults to current directory
#' @param open Logical, whether to open the configuration file for editing
#'
#' @return Invisibly returns TRUE if successful
#' @export
#'
#' @examples \dontrun{
#' # Initialize starlightr for current package
#' use_starlightr()
#'
#' # Initialize for a specific package
#' use_starlightr("/path/to/my/package")
#' }
use_starlightr <- function(pkg = ".", open = interactive()) {
  # Resolve package path
  pkg_path <- normalizePath(pkg, mustWork = TRUE)

  cli::cli_h1("Setting up starlightr for {.pkg {basename(pkg_path)}}")

  # Create _starlightr.toml if it doesn't exist
  config_path <- file.path(pkg_path, "_starlightr.toml")
  if (!file.exists(config_path)) {
    create_default_config(config_path, pkg_path)
    cli::cli_alert_success("Created _starlightr.toml")
  } else {
    cli::cli_alert_info("_starlightr.toml already exists")
  }

  # Update .Rbuildignore
  update_rbuildignore(pkg_path)

  cli::cli_alert_success("starlightr setup complete!")
  cli::cli_bullets(c(
    "*" = "Edit {.file _starlightr.toml} to customize your site",
    "*" = "Run {.fn build_site} to generate your documentation"
  ))

  if (open && file.exists(config_path)) {
    utils::file.edit(config_path)
  }

  invisible(TRUE)
}

#' Create default _starlightr.toml configuration
#'
#' @param config_path Path where to create the config file
#' @param pkg_path Path to package directory
#' @keywords internal
#' @noRd
create_default_config <- function(config_path, pkg_path) {
  # Try to read DESCRIPTION to get package info
  desc_path <- file.path(pkg_path, "DESCRIPTION")
  pkg_name <- basename(pkg_path)
  pkg_desc <- "Documentation generated by starlightr"

  if (file.exists(desc_path)) {
    tryCatch(
      {
        desc_lines <- readLines(desc_path)

        # Extract package name
        name_line <- grep("^Package:", desc_lines, value = TRUE)
        if (length(name_line) > 0) {
          pkg_name <- trimws(sub("^Package:\\s*", "", name_line[1]))
        }

        # Extract description
        desc_line <- grep("^Description:", desc_lines, value = TRUE)
        if (length(desc_line) > 0) {
          pkg_desc <- trimws(sub("^Description:\\s*", "", desc_line[1]))
        }
      },
      error = function(e) {
        # Use defaults if can't read DESCRIPTION
      }
    )
  }

  # Build minimal config - users add sidebar/cards via helpers
  data <- list(
    pkg_name = escape_quoted_string(pkg_name),
    pkg_desc = escape_quoted_string(pkg_desc)
  )

  config_content <- render_template("starlightr.toml", data)

  writeLines(config_content, config_path)
}

#' Update .Rbuildignore to include _starlightr.toml
#'
#' @param pkg_path Path to package directory
#' @keywords internal
#' @noRd
update_rbuildignore <- function(pkg_path) {
  rbuildignore_path <- file.path(pkg_path, ".Rbuildignore")

  # Create .Rbuildignore if it doesn't exist
  if (!file.exists(rbuildignore_path)) {
    writeLines("^_starlightr\\.toml$", rbuildignore_path)
    cli::cli_alert_success("Created .Rbuildignore with _starlightr.toml")
    return()
  }

  # Read existing .Rbuildignore
  existing_lines <- readLines(rbuildignore_path)

  # Check if _starlightr.toml is already ignored
  pattern_exists <- any(grepl("_starlightr", existing_lines, fixed = TRUE))

  if (!pattern_exists) {
    # Add the pattern
    updated_lines <- c(existing_lines, "^_starlightr\\.toml$")
    writeLines(updated_lines, rbuildignore_path)
    cli::cli_alert_success("Updated .Rbuildignore to include _starlightr.toml")
  } else {
    cli::cli_alert_info(
      ".Rbuildignore already includes _starlightr.toml pattern"
    )
  }
}
